# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Sopt27SixthAssignment' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Sopt27SixthAssignment
pod 'Alamofire', '~> 5.2.2'
end
